on:
  push:
     branches: [ master ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "sub_branch"
        github_token: ${{ secrets.GIT_TOKEN }}
